### ISSUE TITLE
You need to include some adapter that implements __karma__.start method!

### ISSUE THREAD

**Issue by hpurmann** [kmees/karma-sinon-chai#38]
After upgrading `karma` to 1.1.0, we got the error ([Travis Build](https://travis-ci.org/actano/yourchoice/builds/140386725))

```
You need to include some adapter that implements __karma__.start method!
```

I found the problem being this plugin. After removing from the karma config, the tests ran again. To make sinon work without this plugin, I used the configuration mentioned here:

https://github.com/sinonjs/sinon/pull/600#issuecomment-162529457

**Comment by Havunen** [comment]
Having same issue here after upgrading to Karma 1.1.0

**Comment by adambrunner** [comment]
Hi, issue had been fixed in v1.2.3

Please upgrade and check it, thanks!

**Comment by callmevlad** [comment]
@adambrunner I'm still seeing this issue with v1.2.3 with:

- `karma@1.1.1`
- `karma-chai@0.1.0`
- `karma-sinon@1.0.5`
- `karma-sinon-chai@1.2.3`
- `sinon@1.17.4`
- `sinon-chai@2.8.0`

Any ideas?

**Comment by hpurmann** [comment]
@callmevlad It's most likely one of the other plugins. Please try to create a minimal use case which only uses `karma-sinon-chai`.

**Comment by reintroducing** [comment]
I'm also having this issue and I have the same dependencies as @callmevlad. In my config I commented out `sinon-chai` and that fixed it so I believe it is still something with this module.  I'm not even running my tests through CI, this is running locally, and I've just started the unit tests on a new project so I only have one test that does some really random assertions just to make sure all my configuration is working properly so I can start writing a test suite.

I'd be happy to provide any information you deem fit to try and help resolve this.

**Comment by reintroducing** [comment]
aaaaaaand foot in mouth, removing the other frameworks from my frameworks array and using just sinon-chai works fine :\  Thats what I get for copy pasting configs, realized this only when I pasted my own frameworks in the prior comment a minute ago, sigh.
